### ISSUE TITLE
login-failed : urora\System\Exceptions\ApiException: ApiException

### ISSUE THREAD

**Issue by hardware** [afterlogic/webmail-lite-8#22]
Hi all,

I can't figure out why imap authentication doesn't work. The webmail does not even try to communicate with the mail server, an exception is thrown before any connection attempt.

I tried with PHP 7.1 and 7.2 without success. No errors in Nginx and PHP logs. This s not an authentication issue on my end, I tried with rainloop without any issue.

Do you have an idea ?

<details>
<summary>Afterlogic Webmail Lite debug logs</summary>

```
[08:38:46.00][b45e63c7] [POST(4)][ip:xx.xx.xx.xx] /?/Api/
[08:38:46.00][b45e63c7] POST > [Module, Method, TenantName, Parameters]
[08:38:46.00][b45e63c7]
[08:38:46.00][b45e63c7] API: StandardLoginFormWebclient::Login
[08:38:46.00][b45e63c7] Execute subscription: AdminAuth::onLogin
[08:38:46.01][b45e63c7] Execute subscription: Mail::onLogin
[08:38:46.01][b45e63c7] Event: 0 > login-failed: contact@domain.tld
[08:38:46.01][b45e63c7] Aurora\System\Exceptions\ApiException: ApiException in /afterlogic-webmail-lite/modules/Core/Module.php:1840

Stack trace:
#0 [internal function]: Aurora\Modules\Core\Module->Login('contact@domain.tld', 'xxxxxxxxxxx', '', false)
#1 /afterlogic-webmail-lite/system/Module/AbstractModule.php(875): call_user_func_array(Array, Array)
#2 /afterlogic-webmail-lite/system/Module/Decorator.php(42): Aurora\System\Module\AbstractModule->CallMethod('Login', Array)
#3 /afterlogic-webmail-lite/modules/StandardLoginFormWebclient/Module.php(45): Aurora\System\Module\Decorator->__call('Login', Array)
#4 [internal function]: Aurora\Modules\StandardLoginFormWebclient\Module->Login('contact@domain.tld', 'xxxxxxxxxxx', '', false)
#5 /afterlogic-webmail-lite/system/Module/AbstractModule.php(875): call_user_func_array(Array, Array)
#6 /afterlogic-webmail-lite/modules/Core/Module.php(535): Aurora\System\Module\AbstractModule->CallMethod('Login', Array, true)
#7 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#8 /afterlogic-webmail-lite/system/Module/AbstractModule.php(620): call_user_func_array(Array, Array)
#9 /afterlogic-webmail-lite/system/Module/Manager.php(690): Aurora\System\Module\AbstractModule->RunEntry('api')
#10 /afterlogic-webmail-lite/system/Application.php(88): Aurora\System\Module\Manager->RunEntry('api')
#11 /afterlogic-webmail-lite/index.php(21): Aurora\System\Application::Start()
#12 {main}
```

</details>

<details>
<summary>Compatibility test</summary>

![](https://i.imgur.com/AbWH7Ow.png)

</details>

<details>
<summary>Mail server settings</summary>

![](https://i.imgur.com/geQd8Em.png)

</details>

Do you need more information ?

Here is my docker image : https://github.com/hardware/afterlogic-webmail-lite

**Comment by afterlogic-support** [comment]
Hello,

There's a couple of possibilities why this may happen. One of them is that domain name isn't found in the list of domains, and it has to be an exact match. The other one is that creating new users on first login is disabled, **AutocreateMailAccountOnNewUserFirstLogin** setting in data/settings/modules/Mail.config.json file controls that.

If none of that helps, we would need a test account on your installation, and admin area access, to help you further. You can send the credentials privately [via HelpDesk](https://s.afterlogic.com/helpdesk).

**Comment by hardware** [comment]
I switched `AutocreateMailAccountOnNewUserFirstLogin` to `true` and, all works now, thank you :)

I'm not sure to understand, why is it necessary to create the account in webmail side while he already exists on the server side ? Why `AutocreateMailAccountOnNewUserFirstLogin` property isn't not set to `true` by default ?

**Comment by afterlogic-support** [comment]
Yes you're right, this setting supposed to be set to true, and I'm quite positive it's set that way by default. I've downloaded [the latest package](https://afterlogic.org/download/webmail-lite-php) and it is set to true there. Did you originally install the product from a ZIP package available on website or in some other way - from Github repository, perhaps?

**Comment by hardware** [comment]
[https://github.com/hardware/afterlogic-webmail-lite/blob/master/Dockerfile#L32](https://github.com/hardware/afterlogic-webmail-lite/blob/42cb1923c59db7f4bfe8f8fe36b96876e8fcd70d/Dockerfile#L32)

I use the link provided in your documentation : 

https://afterlogic.org/download/webmail-lite-php-8.zip
https://afterlogic.com/docs/webmail-lite-8/installation/installation-instructions

**Comment by hardware** [comment]
I found a local zip downloaded (July 16th) with the link above from the official website. 

Here is the content :
 
```json
# data/settings/modules/Mail.config.json

"AutocreateMailAccountOnNewUserFirstLogin": [
    true,
    "bool"
],
```

```json
# modules/Mail/config.json

"AutocreateMailAccountOnNewUserFirstLogin": [
    false,
    "bool"
],
```

```json
# pre-config.json

"Mail": {
    "AllowDefaultAccountForUser": true,
    "AutocreateMailAccountOnNewUserFirstLogin": true
},
```

I'm not sure how this can happens.

**Comment by afterlogic-support** [comment]
I've checked this with the developers, their guess is there was a manual edit of `data/settings/modules/Mail.config.json` file but the syntax in there wasn't valid and the file couldn't be parsed - and in such cases, `modules/Mail/config.json` file would be used as a backup.

**Comment by hardware** [comment]
That makes sense and I found the problem. As you know, I use my docker image to run your webmail, and by default, docker uses the data from the mount point [/afterlogic-webmail-lite/data](https://github.com/hardware/afterlogic-webmail-lite/blob/42cb1923c59db7f4bfe8f8fe36b96876e8fcd70d/Dockerfile#L41) (which is an empty folder by default), and delete all files in data folder, so `data/settings/modules/*` default config files can not used.

I will correct this problem on my side. Thank you for your quick help.
