### ISSUE TITLE
SMTP error : MailSo\Smtp\Exceptions\LoginBadMethodException

### ISSUE THREAD

**Issue by RPSPandora** [afterlogic/webmail-lite-8#26]
Hi, i'm trying using webmail-lite-8 with smtp relay to Postal SMTP on port 25

using : "username/api"
password : "password"

username has/contain  "/" is this a problem?

```
[09:45:33.58][90ea00af] SMTP[NOTICE]: MailSo\Smtp\Exceptions\LoginBadMethodException: MailSo-Smtp-Exceptions-LoginBadMethodException in /home/emailkan/public_html/pakpos/vendor/afterlogic/mailso/lib/MailSo/Smtp/SmtpClient.php:259
Stack trace:
#0 /home/emailkan/public_html/pakpos/modules/Mail/Managers/Main/Manager.php(1292): MailSo\Smtp\SmtpClient->Login('host/ema...', 'r3ekg1whVAemFsF...')
#1 /home/emailkan/public_html/pakpos/modules/Mail/Module.php(3554): Aurora\Modules\Mail\Managers\Main\Manager->sendMessage(Object(Aurora\Modules\Mail\Classes\Account), Object(MailSo\Mime\Message), NULL, 'INBOX.Sent', '', '')
#2 [internal function]: Aurora\Modules\Mail\Module->SendMessage(6, NULL, 600000, Array, '', 'email@gmail...', '', '', 'test', '<div data-crea=...', true, 3, false, Array, '', '', 0, 'INBOX.Sent', '', '', '')
#3 /home/emailkan/public_html/pakpos/system/Module/AbstractModule.php(880): call_user_func_array(Array, Array)
#4 /home/emailkan/public_html/pakpos/modules/Core/Module.php(535): Aurora\System\Module\AbstractModule->CallMethod('SendMessage', Array, true)
#5 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#6 /home/emailkan/public_html/pakpos/system/Module/AbstractModule.php(620): call_user_func_array(Array, Array)
#7 /home/emailkan/public_html/pakpos/system/Module/Manager.php(704): Aurora\System\Module\AbstractModule->RunEntry('api')
#8 /home/emailkan/public_html/pakpos/system/Application.php(88): Aurora\System\Module\Manager->RunEntry('api')
#9 /home/emailkan/public_html/pakpos/index.php(21): Aurora\System\Application::Start()
#10 {main}
[09:45:33.58][90ea00af] SMTP[DATA]: > QUIT\r\n
[09:45:33.77][90ea00af] SMTP[DATA]: < 221 2.0.0 Bye\r\n
[09:45:33.77][90ea00af] SMTP[NOTE]: Disconnected from "tcp://ip:25" (success)
```

**Comment by afterlogic-support** [comment]
Have configured that kind of SMTP use by selecting "Use specified credentials" in properties of mail server used by that account? 
Having "/" character in SMTP login shouldn't be a problem, not that we ever had to deal with that character in login though.

**Comment by RPSPandora** [comment]
hi,

my bad, my postal smtp server running with postfix enabled in ubuntu 16.04 service. 

disable the postfix and it's working.
thanks, btw afterlogic webmail is a great and relaxing webmail app!! 😎
