### ISSUE TITLE
Domain "*" not using full email address as login

### ISSUE THREAD

**Issue by riccardomessineo** [afterlogic/webmail-lite-8#31]
Hi,
  I need to handle multiple domain names on the same webmail.
To do so, I've configured a mail server with domains "*", as suggested on the little text below, and checking "Use full email address as login"

This config however for new users doesn't work, as it will use only the account name when logging in.

```
[15:18:45.73][a1cd232d] [POST(4)][ip:95.239.129.7] /?/Api/
[15:18:45.73][a1cd232d] POST > [Module, Method, TenantName, Parameters]
[15:18:45.73][a1cd232d]
[15:18:45.73][a1cd232d] API: StandardLoginFormWebclient::Login
[15:18:45.73][a1cd232d] Execute subscription: AdminAuth::onLogin
[15:18:45.74][a1cd232d] Execute subscription: Mail::onLogin
[15:18:45.81][a1cd232d] IMAP[NOTE]: Start connection to "ssl://mail.hostedemail.com:993"
[15:18:46.33][a1cd232d] IMAP[DATA]: < * OK IMAP4 ready\r\n
[15:18:46.33][a1cd232d] IMAP[DATA]: > TAG1 CAPABILITY\r\n
[15:18:46.45][a1cd232d] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS IDLE AUTH=PLAIN\r\n
[15:18:46.45][a1cd232d] IMAP[DATA]: < TAG1 OK completed\r\n
[15:18:46.46][a1cd232d] IMAP[SECURE]: > TAG2 LOGIN "test" "********"\r\n
[15:18:49.64][a1cd232d] IMAP[DATA]: < TAG2 NO Invalid\r\n
[15:18:49.64][a1cd232d] IMAP[WARNING]: exception 'MailSo\Imap\Exceptions\NegativeResponseException' with message 'TAG2 NO Invalid' in /var/www/vhosts/webmail-8-lite/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php:1761
Stack trace:
#0 /var/www/vhosts/webmail-8-lite/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(1839): MailSo\Imap\ImapClient->validateResponse(Array)
#1 /var/www/vhosts/webmail-8-lite/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(1710): MailSo\Imap\ImapClient->parseResponseWithValidation(NULL, false)
#2 /var/www/vhosts/webmail-8-lite/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(271): MailSo\Imap\ImapClient->SendRequestWithCheck('LOGIN', Array)
#3 /var/www/vhosts/webmail-8-lite/modules/Mail/Managers/Main/Manager.php(126): MailSo\Imap\ImapClient->Login('test', 'testemail', '')
#4 /var/www/vhosts/webmail-8-lite/modules/Mail/Managers/Main/Manager.php(181): Aurora\Modules\Mail\Managers\Main\Manager->_getImapClient(Object(Aurora\Modules\Mail\Classes\Account))
#5 /var/www/vhosts/webmail-8-lite/modules/Mail/Module.php(5187): Aurora\Modules\Mail\Managers\Main\Manager->validateAccountConnection(Object(Aurora\Modules\Mail\Classes\Account))
#6 [internal function]: Aurora\Modules\Mail\Module->onLogin(Array, false)
#7 /var/www/vhosts/webmail-8-lite/system/Module/Manager.php(364): call_user_func_array(Array, Array)
#8 /var/www/vhosts/webmail-8-lite/system/Module/AbstractModule.php(383): Aurora\System\Module\Manager->broadcastEvent('Core', 'Login', Array, false)
#9 /var/www/vhosts/webmail-8-lite/modules/Core/Module.php(1802): Aurora\System\Module\AbstractModule->broadcastEvent('Login', Array, false)
#10 [internal function]: Aurora\Modules\Core\Module->Login('test@jarrodfath...', 'testemail', '', false)
#11 /var/www/vhosts/webmail-8-lite/system/Module/AbstractModule.php(880): call_user_func_array(Array, Array)
#12 /var/www/vhosts/webmail-8-lite/system/Module/Decorator.php(42): Aurora\System\Module\AbstractModule->CallMethod('Login', Array)
#13 /var/www/vhosts/webmail-8-lite/modules/StandardLoginFormWebclient/Module.php(45): Aurora\System\Module\Decorator->__call('Login', Array)
#14 /var/www/vhosts/webmail-8-lite/modules/StandardLoginFormWebclient/Module.php(45): Aurora\System\Module\Decorator->Login('test@jarrodfath...', 'testemail', '', false)
#15 [internal function]: Aurora\Modules\StandardLoginFormWebclient\Module->Login('test@jarrodfath...', 'testemail', '', false)
#16 /var/www/vhosts/webmail-8-lite/system/Module/AbstractModule.php(880): call_user_func_array(Array, Array)
#17 /var/www/vhosts/webmail-8-lite/modules/Core/Module.php(536): Aurora\System\Module\AbstractModule->CallMethod('Login', Array, true)
#18 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#19 /var/www/vhosts/webmail-8-lite/system/Module/AbstractModule.php(621): call_user_func_array(Array, Array)
#20 /var/www/vhosts/webmail-8-lite/system/Module/Manager.php(690): Aurora\System\Module\AbstractModule->RunEntry('api')
#21 /var/www/vhosts/webmail-8-lite/system/Application.php(89): Aurora\System\Module\Manager->RunEntry('api')
#22 /var/www/vhosts/webmail-8-lite/index.php(21): Aurora\System\Application::Start()
#23 {main}
```

Version 8.2.0-build-a3

**Comment by afterlogic-support** [comment]
> Version 8.2.0-build-a3

There were numerous changes affecting that behavior since 8.2.0, check if the issue persists with the latest 8.2.3 version.

**Comment by riccardomessineo** [comment]
Hi, 
  thank you for your answer.
How can I safely update the software to the 8.2.3?
Which directories should I preserve?

**Comment by afterlogic-support** [comment]
It's mostly about the **data/** directory. You can find the upgrading instructions at:
[https://afterlogic.com/docs/webmail-lite-8/installation/upgrading-instructions](https://afterlogic.com/docs/webmail-lite-8/installation/upgrading-instructions)

**Comment by riccardomessineo** [comment]
Unfortunately, the upgrade didn't fix the bug.
It still uses only the account name as login...

**Comment by afterlogic-support** [comment]
Well, I couldn't reproduce the issue. Have installed the latest 8.2.3 package of WebMail Lite, added a mailserver there with "*" supplied for list of domains, and have successfully logged in.

If you try that on a blank install, are you getting the same issue?

**Comment by riccardomessineo** [comment]
Ok, it works with a fresh install!

Which data should I export->import to the new install?

**Comment by afterlogic-support** [comment]
Other than upgrading with data/ directory preserved, or performing a fresh install, there's no other suggestions I'm afraid.
