### ISSUE TITLE
unable to add accounts

### ISSUE THREAD

**Issue by adamwbb** [afterlogic/webmail-lite-8#98]
I am unable to add any new accounts to my webmail. the account logins work everywhere else but are not generating a database entry in the webmail.

`[01:51:11.55][1bb9f9e0] @Time: 0.002
[01:51:11.55][1bb9f9e0] @TimeApiInit: 0.013
[01:51:11.55][1bb9f9e0] INFO[MEMORY]: Memory peak usage: 2MB
[01:51:11.55][1bb9f9e0] INFO[TIME]: Time delta: 1678153871.5578
[01:51:15.40][2fd866c0]  
[01:51:15.40][2fd866c0]  ===== API: LogsViewerWebclient::GetLogFilesData
[01:51:15.40][2fd866c0] @Time: 0.0017
[01:51:15.40][2fd866c0] @TimeApiInit: 0.0126
[01:51:15.40][2fd866c0] INFO[MEMORY]: Memory peak usage: 2MB
[01:51:15.40][2fd866c0] INFO[TIME]: Time delta: 1678153875.4076
[01:51:16.03][f2b7c682]  
[01:51:16.03][f2b7c682]  ===== API: StandardLoginFormWebclient::Login
[01:51:16.04][f2b7c682] IMAP[NOTE]: Start connection to "tcp://127.0.0.1:143"
[01:51:16.04][f2b7c682] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot ready.\r\n
[01:51:16.04][f2b7c682] IMAP[SECURE]: > TAG1 LOGIN "phantomfox@webbservermc.com" "********"\r\n
[01:51:18.05][f2b7c682] IMAP[DATA]: < TAG1 NO [AUTHENTICATIONFAILED] Authentication failed.\r\n
[01:51:18.05][f2b7c682] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: TAG1 NO (AUTHENTICATIONFAILED) Authentication failed. in /var/www/mail/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php:1774
Stack trace:
#0 /var/www/mail/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(1852): MailSo\Imap\ImapClient->validateResponse()
#1 /var/www/mail/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(1723): MailSo\Imap\ImapClient->parseResponseWithValidation()
#2 /var/www/mail/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(272): MailSo\Imap\ImapClient->SendRequestWithCheck()
#3 /var/www/mail/modules/Mail/Managers/Main/Manager.php(137): MailSo\Imap\ImapClient->Login()
#4 /var/www/mail/modules/Mail/Managers/Main/Manager.php(194): Aurora\Modules\Mail\Managers\Main\Manager->_getImapClient()
#5 /var/www/mail/modules/Mail/Module.php(6603): Aurora\Modules\Mail\Managers\Main\Manager->validateAccountConnection()
#6 [internal function]: Aurora\Modules\Mail\Module->onLogin()
#7 /var/www/mail/system/EventEmitter.php(179): call_user_func_array()
#8 /var/www/mail/system/Module/Manager.php(784): Aurora\System\EventEmitter->emit()
#9 /var/www/mail/system/Module/AbstractModule.php(455): Aurora\System\Module\Manager->broadcastEvent()
#10 /var/www/mail/modules/Core/Module.php(2118): Aurora\System\Module\AbstractModule->broadcastEvent()
#11 [internal function]: Aurora\Modules\Core\Module->Authenticate()
#12 /var/www/mail/system/Module/AbstractModule.php(836): call_user_func_array()
#13 /var/www/mail/system/Module/Decorator.php(55): Aurora\System\Module\AbstractModule->CallMethod()
#14 /var/www/mail/modules/Core/Module.php(2251): Aurora\System\Module\Decorator->__call()
#15 [internal function]: Aurora\Modules\Core\Module->Login()
#16 /var/www/mail/system/Module/AbstractModule.php(836): call_user_func_array()
#17 /var/www/mail/system/Module/Decorator.php(55): Aurora\System\Module\AbstractModule->CallMethod()
#18 /var/www/mail/modules/StandardLoginFormWebclient/Module.php(47): Aurora\System\Module\Decorator->__call()
#19 [internal function]: Aurora\Modules\StandardLoginFormWebclient\Module->Login()
#20 /var/www/mail/system/Module/AbstractModule.php(836): call_user_func_array()
#21 /var/www/mail/modules/Core/Module.php(685): Aurora\System\Module\AbstractModule->CallMethod()
#22 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#23 /var/www/mail/system/Router.php(111): call_user_func_array()
#24 /var/www/mail/system/Module/Manager.php(639): Aurora\System\Router->route()
#25 /var/www/mail/system/Application.php(141): Aurora\System\Module\Manager->RunEntry()
#26 /var/www/mail/system/Application.php(110): Aurora\System\Application->Route()
#27 /var/www/mail/index.php(21): Aurora\System\Application::Start()
#28 {main}
[01:51:18.05][f2b7c682] IMAP[NOTICE]: MailSo\Imap\Exceptions\LoginBadCredentialsException: TAG1 NO (AUTHENTICATIONFAILED) Authentication failed. in /var/www/mail/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php:290
Stack trace:
#0 /var/www/mail/modules/Mail/Managers/Main/Manager.php(137): MailSo\Imap\ImapClient->Login()
#1 /var/www/mail/modules/Mail/Managers/Main/Manager.php(194): Aurora\Modules\Mail\Managers\Main\Manager->_getImapClient()
#2 /var/www/mail/modules/Mail/Module.php(6603): Aurora\Modules\Mail\Managers\Main\Manager->validateAccountConnection()
#3 [internal function]: Aurora\Modules\Mail\Module->onLogin()
#4 /var/www/mail/system/EventEmitter.php(179): call_user_func_array()
#5 /var/www/mail/system/Module/Manager.php(784): Aurora\System\EventEmitter->emit()
#6 /var/www/mail/system/Module/AbstractModule.php(455): Aurora\System\Module\Manager->broadcastEvent()
#7 /var/www/mail/modules/Core/Module.php(2118): Aurora\System\Module\AbstractModule->broadcastEvent()
#8 [internal function]: Aurora\Modules\Core\Module->Authenticate()
#9 /var/www/mail/system/Module/AbstractModule.php(836): call_user_func_array()
#10 /var/www/mail/system/Module/Decorator.php(55): Aurora\System\Module\AbstractModule->CallMethod()
#11 /var/www/mail/modules/Core/Module.php(2251): Aurora\System\Module\Decorator->__call()
#12 [internal function]: Aurora\Modules\Core\Module->Login()
#13 /var/www/mail/system/Module/AbstractModule.php(836): call_user_func_array()
#14 /var/www/mail/system/Module/Decorator.php(55): Aurora\System\Module\AbstractModule->CallMethod()
#15 /var/www/mail/modules/StandardLoginFormWebclient/Module.php(47): Aurora\System\Module\Decorator->__call()
#16 [internal function]: Aurora\Modules\StandardLoginFormWebclient\Module->Login()
#17 /var/www/mail/system/Module/AbstractModule.php(836): call_user_func_array()
#18 /var/www/mail/modules/Core/Module.php(685): Aurora\System\Module\AbstractModule->CallMethod()
#19 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#20 /var/www/mail/system/Router.php(111): call_user_func_array()
#21 /var/www/mail/system/Module/Manager.php(639): Aurora\System\Router->route()
#22 /var/www/mail/system/Application.php(141): Aurora\System\Module\Manager->RunEntry()
#23 /var/www/mail/system/Application.php(110): Aurora\System\Application->Route()
#24 /var/www/mail/index.php(21): Aurora\System\Application::Start()
#25 {main}
[01:51:18.05][f2b7c682] Aurora\System\Exceptions\ApiException: ApiException in /var/www/mail/modules/Core/Module.php:2182
Stack trace:
#0 [internal function]: Aurora\Modules\Core\Module->SetAuthDataAndGetAuthToken()
#1 /var/www/mail/system/Module/AbstractModule.php(836): call_user_func_array()
#2 /var/www/mail/system/Module/Decorator.php(55): Aurora\System\Module\AbstractModule->CallMethod()
#3 /var/www/mail/modules/Core/Module.php(2258): Aurora\System\Module\Decorator->__call()
#4 [internal function]: Aurora\Modules\Core\Module->Login()
#5 /var/www/mail/system/Module/AbstractModule.php(836): call_user_func_array()
#6 /var/www/mail/system/Module/Decorator.php(55): Aurora\System\Module\AbstractModule->CallMethod()
#7 /var/www/mail/modules/StandardLoginFormWebclient/Module.php(47): Aurora\System\Module\Decorator->__call()
#8 [internal function]: Aurora\Modules\StandardLoginFormWebclient\Module->Login()
#9 /var/www/mail/system/Module/AbstractModule.php(836): call_user_func_array()
#10 /var/www/mail/modules/Core/Module.php(685): Aurora\System\Module\AbstractModule->CallMethod()
#11 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#12 /var/www/mail/system/Router.php(111): call_user_func_array()
#13 /var/www/mail/system/Module/Manager.php(639): Aurora\System\Router->route()
#14 /var/www/mail/system/Application.php(141): Aurora\System\Module\Manager->RunEntry()
#15 /var/www/mail/system/Application.php(110): Aurora\System\Application->Route()
#16 /var/www/mail/index.php(21): Aurora\System\Application::Start()
#17 {main}
[01:51:18.05][f2b7c682] @Time: 2.0342
[01:51:18.05][f2b7c682] @TimeApiInit: 0.0097
[01:51:18.05][f2b7c682] INFO[MEMORY]: Memory peak usage: 2MB
[01:51:18.05][f2b7c682] INFO[TIME]: Time delta: 1678153878.0589
[01:51:18.05][f2b7c682] INFO[MEMORY]: Memory peak usage: 2MB
[01:51:18.05][f2b7c682] INFO[TIME]: Time delta: 1678153878.0591
[01:51:18.05][f2b7c682] IMAP[NOTE]: Disconnected from "tcp://127.0.0.1:143" (success)
[01:51:20.51][13ded9b5]  
[01:51:20.51][13ded9b5]  ===== API: LogsViewerWebclient::GetLogFilesData
[01:51:20.51][13ded9b5] @Time: 0.0018
[01:51:20.51][13ded9b5] @TimeApiInit: 0.0132
[01:51:20.51][13ded9b5] INFO[MEMORY]: Memory peak usage: 2MB
[01:51:20.51][13ded9b5] INFO[TIME]: Time delta: 1678153880.518
[01:51:21.79][6cb0fdfc]  
[01:51:21.79][6cb0fdfc]  ===== API: LogsViewerWebclient::GetLog`

**Comment by afterlogic-support** [comment]
From the log file, it looks like you're attempting to log into phantomfox@webbservermc.com IMAP account using local IMAP server, i.e. WebMail is installed on the same host where mail server runs. Are you able to log into that account on that same server with some other IMAP client?
